version: '3.9'

services:
  php_web:
    build:
      context: ./php_app
      dockerfile: Dockerfile.php
    ports:
      - "8080:80" # Access web app via http://localhost:8080
    environment:
      DB_HOST: db_mysql 
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DISPLAY_TABLE_NAME: ${DISPLAY_TABLE_NAME:-books} # relikt of old version 
    volumes:
      - ./php_app:/var/www/html 
    depends_on:
      db_mysql:
        condition: service_healthy 
    restart: unless-stopped

  db_mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME} 
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "${MYSQL_PORT_HOST:-33066}:3306" 
    volumes:
      - mysql_data:/var/lib/mysql 
    healthcheck: # Checks if MySQL is ready to accept connections
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASS}"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s 

volumes:
  mysql_data: 
